# Generated by Django 5.2 on 2025-06-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
    ]
